import type { Consultant, Customer, FinancialData, Plan, Subscription, Transaction, ConsultationNote, Document, User, VirtualPartner } from './types';

export const DEMO_USERS: Record<string, User & { password: string }> = {
  admin: {
    id: 'u1',
    first_name: 'Max',
    last_name: 'Mustermann',
    email: 'admin@finexpert.de',
    password: 'admin',
    role: 'admin',
    company_id: 'c1',
  },
  consultant: {
    id: 'u2',
    first_name: 'Sarah',
    last_name: 'Berger',
    email: 'sarah.berger@finexpert.de',
    password: 'berater',
    role: 'consultant',
    company_id: 'c1',
  },
  customer: {
    id: 'u3',
    first_name: 'Klaus',
    last_name: 'Hoffmann',
    email: 'k.hoffmann@email.de',
    password: 'kunde',
    role: 'customer',
    company_id: 'c1',
  },
};

export const CONSULTANTS: Consultant[] = [
  {
    id: 'cons1',
    first_name: 'Sarah',
    last_name: 'Berger',
    email: 'sarah.berger@finexpert.de',
    phone: '+49 89 12345678',
    mobile: '+49 171 9988776',
    phone_office: '+49 89 12340000',
    address: { street: 'Maximilianstraße', number: '12', zip: '80539', city: 'München' },
    profile_text: 'Zertifizierte Finanzplanerin mit über 10 Jahren Erfahrung in der ganzheitlichen Vermögensberatung. Mein Schwerpunkt liegt auf maßgeschneiderten Altersvorsorge- und Versicherungskonzepten.',
    areas_of_expertise: ['Altersvorsorge', 'Krankenversicherung', 'Berufsunfähigkeit', 'Investmentfonds', 'Immobilienfinanzierung'],
    company_id: 'c1',
    rights: ['ADMIN', 'CONSULTANT', 'CAN_SEE_ALL_CLIENTS', 'CAN_SEE_CLIENTS_OF_LOWER_STAGES'],
    status: 'active',
    customers_count: 8,
    created_at: '2022-03-15',
  },
  {
    id: 'cons2',
    first_name: 'Thomas',
    last_name: 'Weber',
    email: 'thomas.weber@finexpert.de',
    phone: '+49 89 87654321',
    mobile: '+49 172 5544332',
    phone_office: '+49 89 87650000',
    address: { street: 'Leopoldstraße', number: '45', zip: '80802', city: 'München' },
    areas_of_expertise: ['Kapitalanlage', 'Steueroptimierung', 'Unternehmensvorsorge'],
    company_id: 'c1',
    rights: ['CONSULTANT', 'CAN_SEE_ALL_CLIENTS'],
    status: 'active',
    customers_count: 12,
    created_at: '2022-06-01',
  },
  {
    id: 'cons3',
    first_name: 'Anna',
    last_name: 'Schmidt',
    email: 'anna.schmidt@finexpert.de',
    phone: '+49 89 11223344',
    mobile: '+49 173 1122334',
    address: { street: 'Schillerstraße', number: '8', zip: '80336', city: 'München' },
    areas_of_expertise: ['Familienabsicherung', 'Lebensversicherung'],
    company_id: 'c1',
    rights: ['CONSULTANT'],
    status: 'active',
    customers_count: 5,
    created_at: '2023-01-10',
  },
  {
    id: 'cons4',
    first_name: 'Peter',
    last_name: 'Müller',
    email: 'peter.mueller@finexpert.de',
    phone: '+49 89 99887766',
    company_id: 'c1',
    rights: ['CONSULTANT'],
    status: 'inactive',
    customers_count: 0,
    created_at: '2023-08-20',
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: 'cust1',
    first_name: 'Klaus',
    last_name: 'Hoffmann',
    email: 'k.hoffmann@email.de',
    phone: '+49 170 1234567',
    mobile: '+49 176 9988001',
    birth_date: '1978-04-12',
    address: { street: 'Musterstraße 42', zip: '80331', city: 'München' },
    consultant_id: 'cons1',
    consultant_name: 'Sarah Berger',
    company_id: 'c1',
    status: 'active',
    created_at: '2023-02-14',
    last_edited: '2024-01-10',
    sex: 'm',
    personal_wishes: ['Eigenheim', 'Altersvorsorge', 'Reisen'],
    income: 4800,
    income_partner: 2200,
    has_partner: true,
  },
  {
    id: 'cust2',
    first_name: 'Maria',
    last_name: 'Schneider',
    email: 'm.schneider@gmail.com',
    phone: '+49 171 9876543',
    mobile: '+49 177 5544321',
    birth_date: '1985-09-23',
    address: { street: 'Bergweg 7', zip: '80802', city: 'München' },
    consultant_id: 'cons1',
    consultant_name: 'Sarah Berger',
    company_id: 'c1',
    status: 'active',
    created_at: '2023-05-20',
    last_edited: '2024-01-08',
    sex: 'f',
    personal_wishes: ['Altersvorsorge', 'Bildungsfonds'],
    income: 3600,
    has_partner: false,
  },
  {
    id: 'cust3',
    first_name: 'Jürgen',
    last_name: 'Fischer',
    email: 'j.fischer@web.de',
    phone: '+49 172 5551234',
    birth_date: '1965-01-30',
    address: { street: 'Lindenallee 15', zip: '80636', city: 'München' },
    consultant_id: 'cons2',
    consultant_name: 'Thomas Weber',
    company_id: 'c1',
    status: 'active',
    created_at: '2022-11-05',
    last_edited: '2024-01-05',
    sex: 'm',
    personal_wishes: ['Altersvorsorge', 'Immobilien'],
    income: 6200,
    income_partner: 1800,
    has_partner: true,
  },
  {
    id: 'cust4',
    first_name: 'Laura',
    last_name: 'Braun',
    email: 'laura.braun@t-online.de',
    phone: '+49 173 7778888',
    birth_date: '1991-07-14',
    address: { street: 'Rosenstraße 3', zip: '80538', city: 'München' },
    consultant_id: 'cons1',
    consultant_name: 'Sarah Berger',
    company_id: 'c1',
    status: 'active',
    created_at: '2023-09-01',
    last_edited: '2023-12-20',
    sex: 'f',
    personal_wishes: ['Reisen', 'Bildungsfonds'],
    income: 2900,
    has_partner: false,
  },
  {
    id: 'cust5',
    first_name: 'Hans',
    last_name: 'Zimmermann',
    email: 'h.zimmermann@firma.de',
    phone: '+49 174 3334444',
    birth_date: '1958-11-08',
    address: { street: 'Hauptstraße 100', zip: '80331', city: 'München' },
    consultant_id: 'cons2',
    consultant_name: 'Thomas Weber',
    company_id: 'c1',
    status: 'support',
    created_at: '2022-08-15',
    last_edited: '2024-01-12',
    sex: 'm',
    personal_wishes: ['Altersvorsorge'],
    income: 8500,
    income_partner: 3200,
    has_partner: true,
  },
  {
    id: 'cust6',
    first_name: 'Petra',
    last_name: 'Koch',
    email: 'petra.koch@email.de',
    phone: '+49 175 6667777',
    birth_date: '1982-03-19',
    address: { street: 'Gartenweg 22', zip: '80939', city: 'München' },
    consultant_id: 'cons3',
    consultant_name: 'Anna Schmidt',
    company_id: 'c1',
    status: 'active',
    created_at: '2023-11-10',
    last_edited: '2024-01-09',
    sex: 'f',
    personal_wishes: ['Eigenheim', 'Altersvorsorge'],
    income: 3200,
    income_partner: 2800,
    has_partner: true,
  },
  {
    id: 'cust7',
    first_name: 'Markus',
    last_name: 'Wolf',
    email: 'm.wolf@mail.de',
    phone: '+49 176 2223333',
    birth_date: '1975-06-25',
    address: { street: 'Waldstraße 8', zip: '81549', city: 'München' },
    consultant_id: 'cons1',
    consultant_name: 'Sarah Berger',
    company_id: 'c1',
    status: 'inactive',
    created_at: '2022-04-22',
    last_edited: '2023-10-01',
    sex: 'm',
    personal_wishes: ['Immobilien'],
    income: 5100,
    has_partner: false,
  },
  {
    id: 'cust8',
    first_name: 'Julia',
    last_name: 'Richter',
    email: 'julia.richter@online.de',
    phone: '+49 177 8889999',
    birth_date: '1995-12-03',
    address: { street: 'Neustraße 5', zip: '80333', city: 'München' },
    consultant_id: 'cons2',
    consultant_name: 'Thomas Weber',
    company_id: 'c1',
    status: 'active',
    created_at: '2024-01-05',
    last_edited: '2024-01-05',
    sex: 'f',
    personal_wishes: ['Altersvorsorge', 'Reisen'],
    income: 2600,
    has_partner: false,
  },
];

// Virtual partners — keyed by main customer id
// user_id: null marks them as virtual (no login, backend concept)
export const VIRTUAL_PARTNERS: Record<string, VirtualPartner> = {
  cust1: {
    id: 'vp_cust1',
    main_customer_id: 'cust1',
    rel_name: 'spouse',
    user_id: null,
    first_name: 'Anna',
    last_name: 'Hoffmann',
    birth_name: 'Müller',
    sex: 'f',
    birth_date: '1980-06-20',
    city_of_birth: 'Hamburg',
    nationality: 'deutsch',
    email: 'anna.hoffmann@email.de',
    phone: '+49 170 9876543',
    mobile: '+49 170 9876543',
    street: 'Musterstraße 42',
    zip: '80331',
    city: 'München',
    employment: 'angestellt',
    profession: 'Lehrerin',
    employer: 'Städtische Schule München',
    employed_since: '2008-09-01',
    salary_gross: 3100,
    salary_net: 2200,
    kv_type: 'gesetzlich',
    kv_provider: 'AOK Bayern',
    kv_monthly: 310,
    smoker: false,
    retirement_age: 65,
    state_pension: 1100,
    has_bu: false,
    has_life: false,
    created_at: '2023-02-14',
  },
  cust3: {
    id: 'vp_cust3',
    main_customer_id: 'cust3',
    rel_name: 'spouse',
    user_id: null,
    first_name: 'Brigitte',
    last_name: 'Fischer',
    sex: 'f',
    birth_date: '1967-08-14',
    nationality: 'deutsch',
    email: 'b.fischer@web.de',
    phone: '+49 172 5554321',
    street: 'Lindenallee 15',
    zip: '80636',
    city: 'München',
    employment: 'teilzeit',
    profession: 'Verwaltungsangestellte',
    employer: 'Stadt München',
    employed_since: '1995-04-01',
    salary_gross: 2400,
    salary_net: 1800,
    kv_type: 'gesetzlich',
    kv_provider: 'Barmer',
    kv_monthly: 270,
    smoker: false,
    retirement_age: 63,
    state_pension: 900,
    has_bu: false,
    has_life: true,
    life_coverage: 150000,
    created_at: '2022-11-05',
  },
  cust5: {
    id: 'vp_cust5',
    main_customer_id: 'cust5',
    rel_name: 'spouse',
    user_id: null,
    first_name: 'Hildegard',
    last_name: 'Zimmermann',
    sex: 'f',
    birth_date: '1960-03-22',
    nationality: 'deutsch',
    email: 'h.zimmermann@privat.de',
    phone: '+49 174 3335555',
    street: 'Hauptstraße 100',
    zip: '80331',
    city: 'München',
    employment: 'rentner',
    profession: 'Rentnerin (ehem. Ärztin)',
    salary_gross: 0,
    salary_net: 3200,
    kv_type: 'privat',
    kv_provider: 'DKV',
    kv_monthly: 680,
    smoker: false,
    retirement_age: 63,
    state_pension: 3200,
    has_bu: false,
    has_life: false,
    created_at: '2022-08-15',
  },
  cust6: {
    id: 'vp_cust6',
    main_customer_id: 'cust6',
    rel_name: 'partner',
    user_id: null,
    first_name: 'Stefan',
    last_name: 'Koch',
    sex: 'm',
    birth_date: '1980-11-05',
    nationality: 'deutsch',
    email: 's.koch@email.de',
    phone: '+49 175 6668888',
    street: 'Gartenweg 22',
    zip: '80939',
    city: 'München',
    employment: 'selbststaendig',
    profession: 'Softwareentwickler',
    employer: 'Selbständig',
    salary_gross: 4200,
    salary_net: 2800,
    kv_type: 'privat',
    kv_provider: 'Ottonova',
    kv_monthly: 420,
    smoker: false,
    retirement_age: 67,
    state_pension: 800,
    has_bu: true,
    bu_coverage: 3000,
    has_life: false,
    created_at: '2023-11-10',
  },
};

export const FINANCIAL_DATA: Record<string, FinancialData> = {
  cust1: {
    customer_id: 'cust1',
    income: {
      gross_salary: 6800,
      net_salary: 4800,
      partner_gross: 3100,
      partner_net: 2200,
      rental_income: 0,
      other_income: 200,
    },
    expenses: {
      rent: 1450,
      insurance: 380,
      loans: 520,
      living: 1800,
      other: 300,
    },
    retirement: {
      desired_age: 65,
      monthly_need: 3500,
      state_pension: 1820,
      private_pension: 650,
      gap: 1030,
    },
    savings: 28000,
    investments: [
      { id: 'inv1', name: 'ETF-Sparplan', type: 'Fonds', value: 18500, monthly_contribution: 300, return_rate: 7.0 },
      { id: 'inv2', name: 'Tagesgeldkonto', type: 'Sparkonto', value: 9500, monthly_contribution: 100, return_rate: 3.5 },
    ],
    insurances: [
      { id: 'ins1', name: 'Berufsunfähigkeitsversicherung', type: 'BU', provider: 'Allianz', monthly_premium: 89, coverage: 2500, status: 'active' },
      { id: 'ins2', name: 'Risikolebensversicherung', type: 'Leben', provider: 'HUK-Coburg', monthly_premium: 42, coverage: 300000, status: 'active' },
      { id: 'ins3', name: 'Haftpflichtversicherung', type: 'Haftpflicht', provider: 'DEVK', monthly_premium: 8, coverage: 5000000, status: 'active' },
    ],
  },
  cust2: {
    customer_id: 'cust2',
    income: {
      gross_salary: 4900,
      net_salary: 3600,
      rental_income: 0,
      other_income: 0,
    },
    expenses: {
      rent: 1100,
      insurance: 220,
      loans: 0,
      living: 1400,
      other: 250,
    },
    retirement: {
      desired_age: 63,
      monthly_need: 2800,
      state_pension: 1450,
      private_pension: 280,
      gap: 1070,
    },
    savings: 12000,
    investments: [
      { id: 'inv3', name: 'Riester-Rente', type: 'Rente', value: 8200, monthly_contribution: 150, return_rate: 2.5 },
    ],
    insurances: [
      { id: 'ins4', name: 'Private Haftpflicht', type: 'Haftpflicht', provider: 'ERGO', monthly_premium: 6, coverage: 3000000, status: 'active' },
      { id: 'ins5', name: 'Krankentagegeld', type: 'Kranken', provider: 'Axa', monthly_premium: 35, coverage: 80, status: 'active' },
    ],
  },
};

export const PLANS: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price_eur: 0,
    max_consultants: 1,
    isDisabled: {
      download: true,
      companyDesign: true,
      hierarchy: true,
      suggestionReasons: true,
      taaIntegration: true,
      fbExpertIntegration: true,
      dioneraIntegration: true,
      investmentAnalysis: true,
      companyIntroductionPages: true,
    },
  },
  {
    id: 'professional',
    name: 'Professional',
    price_eur: 89,
    max_consultants: 5,
    isDisabled: {
      taaIntegration: true,
      fbExpertIntegration: true,
      dioneraIntegration: true,
      investmentAnalysis: false,
    },
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price_eur: 189,
    max_consultants: 9999,
    isDisabled: {},
  },
];

export const SUBSCRIPTION: Subscription = {
  plan_id: 'professional',
  plan_name: 'Professional',
  status: 'active',
  valid_until: '2025-05-01',
  cancel_at_period_end: false,
};

export const TRANSACTIONS: Transaction[] = [
  { id: 'tx1', date: '2024-04-01', amount: 89, plan_name: 'Professional', status: 'paid', invoice_url: '#' },
  { id: 'tx2', date: '2024-03-01', amount: 89, plan_name: 'Professional', status: 'paid', invoice_url: '#' },
  { id: 'tx3', date: '2024-02-01', amount: 89, plan_name: 'Professional', status: 'paid', invoice_url: '#' },
  { id: 'tx4', date: '2024-01-01', amount: 89, plan_name: 'Professional', status: 'paid', invoice_url: '#' },
  { id: 'tx5', date: '2023-12-01', amount: 89, plan_name: 'Professional', status: 'paid', invoice_url: '#' },
];

export const CONSULTATION_NOTES: Record<string, ConsultationNote[]> = {
  cust1: [
    {
      id: 'note1',
      date: '2024-01-10',
      title: 'Jahresgespräch 2024',
      content: 'Besprochen: Erhöhung ETF-Sparplan auf 350€/Monat. Kunde möchte mittelfristig Immobilienerwerb anstreben. BU-Schutz ausreichend, kein Handlungsbedarf.',
      consultant_name: 'Sarah Berger',
    },
    {
      id: 'note2',
      date: '2023-06-15',
      title: 'Halbjahresgespräch',
      content: 'Gehaltserhöhung um 8% erfolgt. Anpassung der Vorsorgesparbeiträge empfohlen. Risikolebensversicherung durch Geburt des ersten Kindes aufgestockt.',
      consultant_name: 'Sarah Berger',
    },
    {
      id: 'note3',
      date: '2023-01-20',
      title: 'Erstgespräch & Bestandsaufnahme',
      content: 'Vollständige Finanzbestandsaufnahme durchgeführt. Deckungslücke in der Altersvorsorge von ca. 1.030€/Monat identifiziert. Maßnahmenplan erstellt.',
      consultant_name: 'Sarah Berger',
    },
  ],
  cust2: [
    {
      id: 'note4',
      date: '2024-01-08',
      title: 'Quartalgespräch Q1 2024',
      content: 'Riester-Rente läuft planmäßig. Empfehlung: Zusätzliche fondsgebundene Rentenversicherung ab Mitte 2024.',
      consultant_name: 'Sarah Berger',
    },
  ],
};

export const DOCUMENTS: Record<string, Document[]> = {
  cust1: [
    { id: 'doc1', name: 'Beratungsprotokoll_Jan2024.pdf', type: 'pdf', size: '245 KB', created_at: '2024-01-10', url: '#' },
    { id: 'doc2', name: 'Vermögensübersicht_2024.pdf', type: 'pdf', size: '189 KB', created_at: '2024-01-10', url: '#' },
    { id: 'doc3', name: 'BU_Antrag_Allianz.pdf', type: 'pdf', size: '1.2 MB', created_at: '2023-02-14', url: '#' },
    { id: 'doc4', name: 'Erstinformation.pdf', type: 'pdf', size: '98 KB', created_at: '2023-02-14', url: '#' },
  ],
  cust2: [
    { id: 'doc5', name: 'Beratungsprotokoll_Jan2024.pdf', type: 'pdf', size: '210 KB', created_at: '2024-01-08', url: '#' },
    { id: 'doc6', name: 'Riester_Übersicht.pdf', type: 'pdf', size: '156 KB', created_at: '2023-05-20', url: '#' },
  ],
};

export const WISHES_OPTIONS = [
  'Eigenheim', 'Altersvorsorge', 'Reisen', 'Bildungsfonds',
  'Immobilien', 'Unternehmensgründung', 'Frühzeitiger Ruhestand',
  'Finanzielle Unabhängigkeit', 'Schuldenfrei sein', 'Notgroschen aufbauen',
];

export const PRECAUTION_TYPES = [
  { id: 'pt1', type_id: 'nest_egg', name: 'Notgroschen', icon: '🏦', custom_view: 'nest_egg' as const },
  { id: 'pt2', type_id: 'investment', name: 'Investment', icon: '📈' },
  { id: 'pt3', type_id: 'retirement', name: 'Altersvorsorge', icon: '🏖️', custom_view: 'retirement_provisions' as const },
  { id: 'pt4', type_id: 'real_estate', name: 'Immobilie', icon: '🏠' },
  { id: 'pt5', type_id: 'health', name: 'Krankenversicherung', icon: '🏥', custom_view: 'health_insurance' as const },
  { id: 'pt6', type_id: 'decease', name: 'Todesfallleistungen', icon: '🛡️', custom_view: 'decease' as const },
  { id: 'pt7', type_id: 'income', name: 'Einkommensvorsorge', icon: '💼', custom_view: 'income' as const },
  { id: 'pt8', type_id: 'liability', name: 'Privathaftpflicht', icon: '⚖️' },
  { id: 'pt9', type_id: 'property', name: 'Wohngebäude', icon: '🏘️' },
  { id: 'pt10', type_id: 'accident', name: 'Unfall', icon: '🚑' },
  { id: 'pt11', type_id: 'legal', name: 'Rechtsschutz', icon: '📋' },
  { id: 'pt12', type_id: 'travel', name: 'Reiseversicherung', icon: '✈️' },
];

export const CUSTOMER_CONSULTATIONS: Record<string, {
  customer_id: string;
  precautions: import('./types').Precaution[];
  current_state: import('./types').PrecautionContract[];
  suggested_state: import('./types').PrecautionContract[];
}> = {
  cust1: {
    customer_id: 'cust1',
    precautions: [
      { id: 'p1', precaution_type: PRECAUTION_TYPES[0], weighting: 'PROPERTY', property_timespan: 'SHORT', status: 'CONSULTED_BUT_NO_TERMINATION', priority: 1, progress_current_state: 95, progress_suggested_state: 100 },
      { id: 'p2', precaution_type: PRECAUTION_TYPES[1], weighting: 'PROPERTY', property_timespan: 'MEDIUM', status: 'CONSULTATION_WANTED', priority: 2, progress_current_state: 0, progress_suggested_state: 60 },
      { id: 'p3', precaution_type: PRECAUTION_TYPES[2], weighting: 'PROPERTY', property_timespan: 'LONG', status: 'UNDECIDED', priority: 3, progress_current_state: 45, progress_suggested_state: 80 },
      { id: 'p4', precaution_type: PRECAUTION_TYPES[3], weighting: 'PROPERTY', property_timespan: 'LONG', status: 'UNDECIDED', priority: 4, progress_current_state: 0, progress_suggested_state: 0 },
      { id: 'p5', precaution_type: PRECAUTION_TYPES[4], weighting: 'VERRY_IMPORTANT', status: 'CONSULTED_BUT_NO_TERMINATION', priority: 5, progress_current_state: 100, progress_suggested_state: 100 },
      { id: 'p6', precaution_type: PRECAUTION_TYPES[5], weighting: 'VERRY_IMPORTANT', status: 'UNDECIDED', priority: 6, progress_current_state: 0, progress_suggested_state: 70 },
      { id: 'p7', precaution_type: PRECAUTION_TYPES[6], weighting: 'VERRY_IMPORTANT', status: 'CONSULTATION_WANTED', priority: 7, progress_current_state: 75, progress_suggested_state: 90 },
      { id: 'p8', precaution_type: PRECAUTION_TYPES[7], weighting: 'IMPORTANT', status: 'CONSULTED_BUT_NO_TERMINATION', priority: 8, progress_current_state: 85, progress_suggested_state: 85 },
      { id: 'p9', precaution_type: PRECAUTION_TYPES[8], weighting: 'IMPORTANT', status: 'CONSULTATION_WANTED', priority: 9, progress_current_state: 76, progress_suggested_state: 76 },
      { id: 'p10', precaution_type: PRECAUTION_TYPES[9], weighting: 'IMPORTANT', status: 'UNDECIDED', priority: 10, progress_current_state: 0, progress_suggested_state: 50 },
      { id: 'p11', precaution_type: PRECAUTION_TYPES[10], weighting: 'IMPORTANT', status: 'UNDECIDED', priority: 11, progress_current_state: 0, progress_suggested_state: 40 },
      { id: 'p12', precaution_type: PRECAUTION_TYPES[11], weighting: 'NICE_TO_HAVE', status: 'NO_CONSULTATION_WANTED', priority: 12, progress_current_state: 0, progress_suggested_state: 0 },
    ],
    current_state: [
      { id: 'cs1', precaution_type_id: 'pt1', company: 'Sparkasse', tariff: 'Tagesgeld', fee: 0, payment_frequency: 'monthly', percentage: 95 },
      { id: 'cs2', precaution_type_id: 'pt5', company: 'AOK', tariff: 'Gesetzlich', fee: 420, payment_frequency: 'monthly', percentage: 100 },
      { id: 'cs3', precaution_type_id: 'pt7', company: 'Allianz', tariff: 'BU Klassik', fee: 89, payment_frequency: 'monthly', percentage: 75 },
      { id: 'cs4', precaution_type_id: 'pt8', company: 'ERGO', tariff: 'Haftpflicht Plus', fee: 8, payment_frequency: 'monthly', percentage: 85 },
      { id: 'cs5', precaution_type_id: 'pt9', company: 'HUK-COBURG', tariff: 'WohngebäudeKomfort', fee: 55, payment_frequency: 'monthly', percentage: 76 },
      { id: 'cs6', precaution_type_id: 'pt3', company: 'Deutsche Rentenversicherung', tariff: 'Gesetzliche Rente', fee: 310, payment_frequency: 'monthly', percentage: 45 },
    ],
    suggested_state: [
      { id: 'ss1', precaution_type_id: 'pt2', company: 'DWS', tariff: 'ETF Portfolio', fee: 100, payment_frequency: 'monthly', percentage: 60, customer_wishes_contract: true },
      { id: 'ss2', precaution_type_id: 'pt3', company: 'Allianz', tariff: 'Riester Rente', fee: 150, payment_frequency: 'monthly', percentage: 35, customer_wishes_contract: false },
      { id: 'ss3', precaution_type_id: 'pt6', company: 'Zurich', tariff: 'Risikoleben', fee: 25, payment_frequency: 'monthly', percentage: 70, customer_wishes_contract: true },
      { id: 'ss4', precaution_type_id: 'pt10', company: 'DEVK', tariff: 'Unfall Premium', fee: 12, payment_frequency: 'monthly', percentage: 50, customer_wishes_contract: false },
      { id: 'ss5', precaution_type_id: 'pt11', company: 'ARAG', tariff: 'Rechtsschutz Basis', fee: 18, payment_frequency: 'monthly', percentage: 40, customer_wishes_contract: false },
    ],
  },
  cust2: {
    customer_id: 'cust2',
    precautions: [
      { id: 'q1', precaution_type: PRECAUTION_TYPES[0], weighting: 'PROPERTY', property_timespan: 'SHORT', status: 'UNDECIDED', priority: 1, progress_current_state: 50, progress_suggested_state: 100 },
      { id: 'q2', precaution_type: PRECAUTION_TYPES[2], weighting: 'PROPERTY', property_timespan: 'LONG', status: 'CONSULTATION_WANTED', priority: 2, progress_current_state: 30, progress_suggested_state: 70 },
      { id: 'q3', precaution_type: PRECAUTION_TYPES[4], weighting: 'VERRY_IMPORTANT', status: 'CONSULTED_BUT_NO_TERMINATION', priority: 3, progress_current_state: 100, progress_suggested_state: 100 },
      { id: 'q4', precaution_type: PRECAUTION_TYPES[6], weighting: 'VERRY_IMPORTANT', status: 'UNDECIDED', priority: 4, progress_current_state: 40, progress_suggested_state: 80 },
      { id: 'q5', precaution_type: PRECAUTION_TYPES[7], weighting: 'IMPORTANT', status: 'UNDECIDED', priority: 5, progress_current_state: 60, progress_suggested_state: 85 },
    ],
    current_state: [
      { id: 'qc1', precaution_type_id: 'pt1', company: 'ING', tariff: 'Extra-Konto', fee: 0, payment_frequency: 'monthly', percentage: 50 },
      { id: 'qc2', precaution_type_id: 'pt5', company: 'TK', tariff: 'Gesetzlich', fee: 395, payment_frequency: 'monthly', percentage: 100 },
      { id: 'qc3', precaution_type_id: 'pt7', company: 'Generali', tariff: 'BU Basis', fee: 65, payment_frequency: 'monthly', percentage: 40 },
      { id: 'qc4', precaution_type_id: 'pt8', company: 'AXA', tariff: 'Haftpflicht Basis', fee: 7, payment_frequency: 'monthly', percentage: 60 },
    ],
    suggested_state: [],
  },
};

export const COMPANY_INFO = {
  id: 'c1',
  name: 'Finanz & Vorsorge GmbH',
  logo: null,
  primary_color: '#125267',
  secondary_color: '#759ad9',
  address: 'Maximilianstraße 12, 80539 München',
  phone: '+49 89 45678900',
  email: 'info@finanzvorsorge.de',
  website: 'www.finanzvorsorge.de',
};
